### ISSUE TITLE
Fehler beim ID-Harvesten der OAI-Schnittstelle der SHLB (mets)

### ISSUE THREAD

**Issue by tschleier** [Deutsche-Digitale-Bibliothek/ddblabs-ometha#4]
Beim ID-Harvesten der [OAI-Schnittstelle der SHLB](https://digibib.schleswig-holstein.de/oai) läuft Ometha in den neueren Versionen in 403er Fehler. Mit 1.8.2 funktionerte das ID-Harvesten.

Getestet mit den Versionen1.9.6 und 1.9.8 unter Windows (aktuelle Dev s. u.)

Beispiel:

`Test.yaml`
```yaml
date: 2024-02-25T08:46:14Z
url: https://digibib.schleswig-holstein.de/oai
set: ['komplett']
mprefix: mets
ids:
- '367996243-575'
- '345723538-246'
- '362265674-251'
- '715940368-578'
- '296'
- '595'
- '450039164-231'
- '450039033-236'
- 'DE-611-HS-3529957-47'
- 'DE-611-HS-3792628-122'
```

Aufruf jeweils:
`Ometha.exe ids --idfile Test.yaml`

Log:
```
2024-03-07 15:04:07.163 | PARAMETER | Harvestingvorgang mit Ometha 1.9.6 gestartet
2024-03-07 15:04:07.163 | PARAMETER | Modus: Frozen/executable with cli Mode
2024-03-07 15:04:07.164 | PARAMETER | Datengeber: 20240307150407
2024-03-07 15:04:07.164 | PARAMETER | Base-URL: https://digibib.schleswig-holstein.de/oai
2024-03-07 15:04:07.164 | PARAMETER | metadataPrefix: mets
2024-03-07 15:04:07.164 | PARAMETER | Sets: ['komplett']
2024-03-07 15:04:07.164 | PARAMETER | Timeout: 0.0
2024-03-07 15:04:07.164 | PARAMETER | Outputfolder: C:\temp\ometha
2024-03-07 15:04:07.165 | PARAMETER | Count of parallel downloads: 16
2024-03-07 15:04:07.436 | INFO     | Harveste mit ID File
2024-03-07 15:04:07.583 | INFO     | Anzahl der parallelen Download Vorgänge auf 4 gesetzt auf Basis der Anzahl an IDs.
2024-03-07 15:04:07.591 | INFO     | Harveste 10 IDs.
2024-03-07 15:04:09.202 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=DE-611-HS-3529957-47 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.242 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=362265674-251 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.379 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=450039164-231 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.412 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=296 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.422 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=367996243-575 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.429 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=595 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.581 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=345723538-246 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.599 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=450039033-236 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.607 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=715940368-578 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.614 | WARNING  | Return von https://digibib.schleswig-holstein.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=DE-611-HS-3792628-122 unwahrscheinlich klein (0.146) Kilobytes
2024-03-07 15:04:09.695 | INFO     | Harvesting beendet
2024-03-07 15:04:09.696 | INFO     | Programm beendet.
2024-03-07 15:04:09.700 | DEBUG    | Zeit: 2.2602120260000005 Sekunden
```

Die geharvesteten "Datensätze" enthalten jeweils

```html
<html>

<head><title>403 Forbidden</title></head>

<body>

<center><h1>403 Forbidden</h1></center>

<hr><center>nginx</center>

</body>

</html>
```

Die im Log genannten URLs sind im Browser ohne den Fehler aufrufbar.

In der aktuellen Dev-Version startet das ID-Harvesten nicht und bricht mit folgendem Fehler ab:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\schleier\AppData\Local\Programs\Python\Python312\Scripts\ometha.exe\__main__.py", line 7, in <module>
  File "C:\Users\schleier\AppData\Local\Programs\Python\Python312\Lib\site-packages\ometha\main.py", line 154, in start_process
    PRM["b_url"] = re.sub(r"(\?.+)", "", PRM["b_url"]).rstrip("/")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schleier\AppData\Local\Programs\Python\Python312\Lib\re\__init__.py", line 186, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

**Comment by karkraeg** [comment]
Hi @tschleier versuch es bitte mit dem neusten Stand von develop nochmal. Damit funktioniert es sowohl mit

```
ometha default -b https://digibib.schleswig-holstein.de/oai -m mets -d SLW
```

als auch mit der `Test.yaml`, wobei ich den Key von `set` auf `sets` geändert habe. Ich muss wirklich mal Tests schreiben um alle Fälle abzudecken.

**Comment by tschleier** [comment]
Hallo @karkraeg,
das normale Harvesten geht mit der aktuellen Version.
Wenn ich es aber mit `ometha ids --idfile Test.yaml`  (`set` zu `sets` korrigiert) probiere, ignoriert Ometha das und harvestet einfach komplett anstatt die 10 Datensätze. 😅

**Comment by karkraeg** [comment]
Müsste jetzt auch gehen!

**Comment by tschleier** [comment]
Danke, funktioniert.👍
